### ISSUE TITLE
ActiveMQ

### ISSUE THREAD

**Issue by RickdeGier** [CymaticLabs/Unity3D.Amqp#9]
Can I use Unity3D.Amqp to connect to a ActiveMQ broker using AMQP (ActiveMQ supports it) because the readme is saying it supports rabbitMQ?

**Comment by meverett** [comment]
I'm guessing the answer is probably no. It looks like ActiveMQ implements AMQP 1.0 where as RabbitMQ is version 0.9.1. If you check out the AMQP 1.0 section [on this RabbitMQ page](https://www.rabbitmq.com/protocols.html) it indicates that the two versions are very different implementations down to the wire, so it's more like two different protocols than the same. Plus the version of the C# RabbitMQ client used in this project is also much older than the current one because of .NET support issues within Unity (although with latest versions of Unity this may be resolved, but would require implementing a whole new C# RabbitMQ client into this project).

**Comment by RickdeGier** [comment]
Thank you
